name: environment.yml
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - plotly
  - missingno
  - xlrd
  - Final_Projects_Su2020/screenshots/11.Full.PNG
  # from https://github.com/binder-examples/conda
